// src/screens/event/templates/wedding/WeddingStyles.js
import { StyleSheet, Platform } from 'react-native';
import { width, height, KoreanColors } from './WeddingUtils';

const styles = StyleSheet.create({
  // =================================================================
  // 공통 컴포넌트 스타일
  // =================================================================
  petalsContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    zIndex: 1000,
    pointerEvents: 'none',
  },
  petal: {
    position: 'absolute',
    zIndex: 1,
  },
  petalText: {
    fontSize: 16,
    opacity: 0.7,
  },
  heartsContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    zIndex: 999,
    pointerEvents: 'none',
  },
  floatingHeart: {
    position: 'absolute',
    fontSize: 20,
    bottom: height - 100,
  },
  heartIcon: {
    fontSize: 24,
  },
  
  // 오프닝 오버레이 스타일 (새로 추가)
  openingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(0,0,0,0.7)',
    zIndex: 9999,
    justifyContent: 'center',
    alignItems: 'center',
  },
  openingContent: {
    alignItems: 'center',
  },
  openingText: {
    fontFamily: Platform.OS === 'ios' ? 'Great Vibes' : 'serif',
    fontSize: 48,
    color: '#ffffff',
    fontStyle: 'italic',
  },
  
  // 방명록 스타일 (새로 추가)
  guestbookContainer: {
    width: '100%',
    maxWidth: 400,
    alignSelf: 'center',
  },
  messageCard: {
    backgroundColor: '#ffffff',
    borderRadius: 15,
    padding: 25,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.05,
    shadowRadius: 15,
    elevation: 5,
  },
  messageHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 15,
  },
  messageFrom: {
    color: '#999',
    fontSize: 14,
  },
  messageDate: {
    color: '#DDD',
    fontSize: 12,
  },
  messageContent: {
    fontSize: 15,
    lineHeight: 24,
    color: '#555',
  },
  messageButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#C2B0A2',
    paddingVertical: 18,
    borderRadius: 30,
    marginTop: 30,
  },
  messageButtonIcon: {
    fontSize: 20,
    marginRight: 8,
  },
  messageButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
  },
  
  // 계좌 토글 스타일 (새로 추가)
  accountToggleContainer: {
    width: '100%',
    maxWidth: 400,
    alignSelf: 'center',
  },
  toggleItem: {
    marginBottom: 15,
    borderRadius: 15,
    overflow: 'hidden',
    backgroundColor: '#ffffff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.08,
    shadowRadius: 20,
    elevation: 8,
  },
  toggleItemActive: {
    shadowOpacity: 0.15,
  },
  toggleHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#C2B0A2',
    padding: 20,
  },
  toggleTitle: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
  },
  toggleArrow: {
    color: '#ffffff',
    fontSize: 18,
  },
  toggleContent: {
    backgroundColor: '#ffffff',
    padding: 25,
  },
  accountBank: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 8,
  },
  accountNumber: {
    fontSize: 18,
    color: '#555',
    marginBottom: 5,
  },
  accountName: {
    fontSize: 14,
    color: '#999',
    marginBottom: 15,
  },
  copyButton: {
    backgroundColor: '#FFE0EC',
    paddingHorizontal: 25,
    paddingVertical: 10,
    borderRadius: 20,
    alignSelf: 'flex-start',
  },
  copyButtonText: {
    color: '#666',
    fontSize: 14,
  },
  
  // 카운트다운 공통 스타일
  countdownContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 15,
  },
  countdownItem: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: 15,
    padding: 15,
    minWidth: 60,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  countdownNumber: {
    fontSize: 24,
    fontWeight: '700',
    color: '#ffffff',
    marginBottom: 5,
  },
  countdownLabel: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.8)',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  countdownExpired: {
    alignItems: 'center',
    padding: 20,
  },
  countdownExpiredText: {
    fontSize: 20,
    fontWeight: '700',
    color: '#ffffff',
    textAlign: 'center',
  },
  
  // 이미지 뷰어
  imageViewerContainer: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.9)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  imageViewerClose: {
    position: 'absolute',
    top: 50,
    right: 20,
    zIndex: 10,
    padding: 10,
  },
  imageViewerContent: {
    width: '100%',
    height: '70%',
  },
  imageViewerImage: {
    width: '100%',
    height: '100%',
  },
  imageViewerIndicator: {
    position: 'absolute',
    bottom: 50,
    alignSelf: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 20,
  },
  imageViewerCounter: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '500',
  },

  // 메인 포토 슬라이드쇼
  mainPhotoSlideshow: {
    width: '100%',
    height: height * 0.6,
    position: 'relative',
  },
  mainPhotoImage: {
    width: '100%',
    height: '100%',
  },
  mainPhotoIndicators: {
    position: 'absolute',
    bottom: 20,
    alignSelf: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  mainPhotoIndicator: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#ffffff',
  },

  // 갤러리
  galleryAutoSlide: {
    width: '100%',
    height: 300,
    borderRadius: 20,
    overflow: 'hidden',
    position: 'relative',
  },
  galleryAutoSlideImage: {
    width: '100%',
    height: '100%',
  },
  galleryAutoSlideIndicators: {
    position: 'absolute',
    bottom: 15,
    alignSelf: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  galleryIndicator: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#ffffff',
  },
  galleryScroll: {
    width: '100%',
    height: 300,
  },
  galleryItem: {
    width: width - 60,
    height: 300,
    marginHorizontal: 15,
    borderRadius: 20,
    overflow: 'hidden',
  },
  galleryItemImage: {
    width: '100%',
    height: '100%',
  },

  // =================================================================
  // 로맨틱 핑크 달력 스타일 (새로 추가)
  // =================================================================
  romanticCalendar: {
    width: '100%',
    maxWidth: 350,
    alignSelf: 'center',
    marginVertical: 30,
  },
  romanticCalendarContainer: {
    backgroundColor: '#ffffff',
    borderRadius: 15,
    padding: 30,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 30,
    elevation: 8,
  },
  romanticCalendarHeader: {
    alignItems: 'center',
    marginBottom: 25,
  },
  romanticCalendarTitle: {
    fontSize: 20,
    fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
    color: '#333',
    fontWeight: '500',
  },
  romanticCalendarWeekDays: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 15,
  },
  romanticCalendarWeekDay: {
    fontSize: 11,
    fontWeight: '500',
    color: '#666',
    width: 35,
    textAlign: 'center',
  },
  romanticCalendarSunday: {
    color: '#ff6b6b',
  },
  romanticCalendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  romanticCalendarDayContainer: {
    width: '14.28%',
    aspectRatio: 1,
    padding: 2,
  },
  romanticCalendarDay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
  },
  romanticCalendarWeddingDay: {
    backgroundColor: '#C2B0A2',
    shadowColor: '#C2B0A2',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 15,
    elevation: 8,
  },
  romanticCalendarDayText: {
    fontSize: 13,
    color: '#666',
  },
  romanticCalendarWeddingDayText: {
    fontSize: 14,
    color: '#ffffff',
    fontWeight: '600',
  },
  romanticCalendarOtherMonthText: {
    color: 'transparent',
  },
  romanticCalendarSundayText: {
    color: '#ff6b6b',
  },

  // =================================================================
  // 로맨틱 핑크 템플릿 스타일 (새로 추가)
  // =================================================================
  romantic_container: {
    flex: 1,
    backgroundColor: '#E7DFDA',
  },
  romantic_scrollView: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  
  // 인트로 섹션
  romantic_introSection: {
    minHeight: height,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 20,
    paddingHorizontal: 20,
    position: 'relative',
  },
  romantic_introContent: {
    alignItems: 'center',
    zIndex: 2,
  },
  romantic_subtitle: {
    fontSize: 12,
    color: '#C2B0A2',
    letterSpacing: 3,
    marginBottom: 10,
  },
  romantic_loveText: {
    fontFamily: Platform.OS === 'ios' ? 'Dancing Script' : 'cursive',
    fontSize: 64,
    color: '#9B8D82',
    marginVertical: 15,
    fontWeight: '400',
  },
  romantic_mainImageContainer: {
    width: width * 0.95,
    maxWidth: 420,
    height: 650,
    borderRadius: 320,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    overflow: 'hidden',
    marginTop: 20,
    shadowColor: '#C2B0A2',
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.2,
    shadowRadius: 60,
    elevation: 15,
  },
  romantic_mainPhoto: {
    width: '100%',
    height: '100%',
  },
  
  // 인사말 섹션
  romantic_greetingSection: {
    backgroundColor: '#ffffff',
    paddingVertical: 100,
    paddingHorizontal: 35,
    alignItems: 'center',
  },
  romantic_floatingHeart: {
    marginBottom: 30,
  },
  romantic_heartPulse: {
    fontSize: 32,
  },
  romantic_poem: {
    fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
    fontSize: 16,
    lineHeight: 32,
    color: '#666',
    textAlign: 'center',
    marginVertical: 40,
    fontWeight: '300',
  },
  romantic_divider: {
    width: 60,
    height: 1,
    backgroundColor: '#9B8D82',
    opacity: 0.3,
    marginVertical: 40,
  },
  romantic_coupleNames: {
    fontSize: 17,
    color: '#666',
  },
  romantic_boldText: {
    fontWeight: '600',
  },
  
  // 갤러리 섹션
  romantic_gallerySection: {
    backgroundColor: '#ffffff',
    paddingVertical: 80,
    overflow: 'hidden',
  },
  romantic_galleryTitle: {
    fontFamily: Platform.OS === 'ios' ? 'Playfair Display' : 'serif',
    fontSize: 40,
    color: '#333',
    fontStyle: 'italic',
    textAlign: 'center',
    marginBottom: 10,
  },
  romantic_gallerySubtitle: {
    fontSize: 14,
    color: '#999',
    textAlign: 'center',
    marginBottom: 40,
  },
  romantic_gallerySlider: {
    paddingLeft: 40,
  },
  romantic_galleryItem: {
    width: width * 0.75,
    height: 350,
    marginRight: 15,
    borderRadius: 15,
    overflow: 'hidden',
    backgroundColor: '#F0EBE6',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.08,
    shadowRadius: 20,
    elevation: 8,
  },
  romantic_galleryImage: {
    width: '100%',
    height: '100%',
  },
  romantic_galleryDots: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 10,
    marginTop: 30,
  },
  romantic_dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#ddd',
  },
  romantic_dotActive: {
    backgroundColor: '#9B8D82',
    width: 30,
    borderRadius: 4,
  },
  
  // 날짜 섹션
  romantic_dateSection: {
    paddingVertical: 100,
    alignItems: 'center',
    position: 'relative',
  },
  romantic_dateTextLarge: {
    fontFamily: Platform.OS === 'ios' ? 'Dancing Script' : 'cursive',
    fontSize: 64,
    color: '#ffffff',
    marginBottom: 20,
  },
  romantic_dateSubtext: {
    fontSize: 17,
    color: '#ffffff',
    opacity: 0.9,
  },
  
  // Wedding Day 섹션
  romantic_weddingDaySection: {
    backgroundColor: '#ffffff',
    paddingVertical: 80,
    paddingHorizontal: 20,
  },
  romantic_weddingDayTitle: {
    fontFamily: Platform.OS === 'ios' ? 'Playfair Display' : 'serif',
    fontSize: 40,
    color: '#333',
    fontStyle: 'italic',
    textAlign: 'center',
    marginBottom: 40,
  },
  romantic_dateInfo: {
    alignItems: 'center',
    marginBottom: 30,
  },
  romantic_dateMain: {
    fontSize: 17,
    color: '#333',
    marginBottom: 10,
  },
  romantic_dateSub: {
    fontSize: 14,
    color: '#999',
  },
  romantic_calendar: {
    marginBottom: 30,
  },
  romantic_countdown: {
    marginBottom: 30,
  },
  romantic_countdownGrid: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 12,
  },
  romantic_countdownNumber: {
    fontSize: 28,
    fontFamily: Platform.OS === 'ios' ? 'Playfair Display' : 'serif',
    color: '#333',
    fontWeight: '300',
  },
  romantic_countdownLabel: {
    fontSize: 10,
    color: '#999',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginTop: 8,
  },
  romantic_countdownMessage: {
    fontSize: 17,
    color: '#666',
    textAlign: 'center',
  },
  romantic_heartText: {
    color: '#C2B0A2',
    fontSize: 20,
  },
  romantic_countdownDays: {
    color: '#9B8D82',
    fontWeight: '500',
  },
  
  // 커플 섹션
  romantic_coupleSection: {
    paddingVertical: 80,
    paddingHorizontal: 20,
    position: 'relative',
  },
  romantic_coupleTitle: {
    fontFamily: Platform.OS === 'ios' ? 'Playfair Display' : 'serif',
    fontSize: 40,
    color: '#333',
    fontStyle: 'italic',
    textAlign: 'center',
    marginBottom: 50,
  },
  romantic_coupleCards: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 20,
    flexWrap: 'wrap',
  },
  romantic_coupleCard: {
    flex: 1,
    minWidth: 140,
    backgroundColor: '#ffffff',
    borderRadius: 20,
    padding: 30,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.08,
    shadowRadius: 30,
    elevation: 8,
  },
  romantic_couplePhotoContainer: {
    width: 150,
    height: 150,
    borderRadius: 75,
    overflow: 'hidden',
    marginBottom: 25,
    backgroundColor: '#FFE0EC',
  },
  romantic_couplePhoto: {
    width: '100%',
    height: '100%',
  },
  romantic_coupleRole: {
    backgroundColor: '#C2B0A2',
    color: '#ffffff',
    paddingHorizontal: 18,
    paddingVertical: 6,
    borderRadius: 20,
    fontSize: 12,
    marginBottom: 15,
    overflow: 'hidden',
  },
  romantic_coupleName: {
    fontSize: 26,
    fontWeight: '500',
    color: '#333',
    marginBottom: 5,
  },
  romantic_coupleEngName: {
    fontSize: 14,
    color: '#999',
    marginBottom: 20,
  },
  romantic_coupleParents: {
    fontSize: 14,
    color: '#666',
    lineHeight: 24,
    textAlign: 'center',
    marginBottom: 15,
  },
  romantic_coupleInfo: {
    fontSize: 13,
    color: '#999',
    lineHeight: 20,
    textAlign: 'center',
  },
  
  // 메시지 섹션
  romantic_messagesSection: {
    paddingVertical: 80,
    paddingHorizontal: 20,
    position: 'relative',
  },
  romantic_messagesTitle: {
    fontFamily: Platform.OS === 'ios' ? 'Playfair Display' : 'serif',
    fontSize: 40,
    color: '#333',
    fontStyle: 'italic',
    textAlign: 'center',
    marginBottom: 10,
  },
  romantic_messagesSubtitle: {
    fontSize: 14,
    color: '#999',
    textAlign: 'center',
    marginBottom: 40,
  },
  
  // 위치 섹션
  romantic_locationSection: {
    backgroundColor: '#ffffff',
    paddingVertical: 80,
    paddingHorizontal: 20,
  },
  romantic_locationTitle: {
    fontFamily: Platform.OS === 'ios' ? 'Playfair Display' : 'serif',
    fontSize: 40,
    color: '#333',
    fontStyle: 'italic',
    textAlign: 'center',
    marginBottom: 40,
  },
  romantic_venueInfo: {
    alignItems: 'center',
    marginBottom: 40,
  },
  romantic_venueName: {
    fontSize: 20,
    color: '#333',
    fontWeight: '500',
    marginBottom: 10,
  },
  romantic_venueAddress: {
    fontSize: 15,
    color: '#666',
  },
  romantic_mapContainer: {
    height: 300,
    backgroundColor: '#F0EBE6',
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 40,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.08,
    shadowRadius: 30,
    elevation: 8,
  },
  romantic_mapContainerReal: {
    height: 300,
    borderRadius: 20,
    overflow: 'hidden',
    marginBottom: 40,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.08,
    shadowRadius: 30,
    elevation: 8,
  },
  romantic_mapPlaceholder: {
    fontSize: 48,
    marginBottom: 10,
  },
  romantic_mapText: {
    fontSize: 14,
    color: '#999',
  },
  romantic_transportCard: {
    flexDirection: 'row',
    backgroundColor: '#F8F5F2',
    borderRadius: 20,
    padding: 30,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.05,
    shadowRadius: 20,
    elevation: 5,
  },
  romantic_transportIcon: {
    marginRight: 20,
    fontSize: 24,
  },
  romantic_transportContent: {
    flex: 1,
  },
  romantic_transportTitle: {
    fontSize: 18,
    color: '#C2B0A2',
    marginBottom: 10,
    fontWeight: '500',
  },
  romantic_transportText: {
    fontSize: 14,
    color: '#666',
    lineHeight: 24,
  },
  romantic_navigationButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#9B8D82',
    paddingVertical: 15,
    borderRadius: 25,
  },
  romantic_navigationText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8,
  },
  
  // 계좌 섹션
  romantic_accountSection: {
    paddingVertical: 80,
    paddingHorizontal: 20,
    position: 'relative',
  },
  romantic_accountTitle: {
    fontFamily: Platform.OS === 'ios' ? 'Playfair Display' : 'serif',
    fontSize: 40,
    color: '#333',
    fontStyle: 'italic',
    textAlign: 'center',
    marginBottom: 20,
  },
  romantic_accountSubtitle: {
    fontSize: 14,
    color: '#999',
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 50,
  },
  
  // 계좌번호 섹션
  romantic_accountSection: {
    paddingVertical: 40,
    paddingHorizontal: 20,
    backgroundColor: '#FFF5F5',
    borderTopWidth: 1,
    borderTopColor: '#E8E4E0',
    borderBottomWidth: 1,
    borderBottomColor: '#E8E4E0',
  },
  romantic_accountTitle: {
    fontSize: 28,
    fontWeight: '600',
    color: '#8B6F47',
    textAlign: 'center',
    marginBottom: 12,
    fontFamily: 'System',
  },
  romantic_accountSubtitle: {
    fontSize: 16,
    color: '#9B8D82',
    textAlign: 'center',
    marginBottom: 30,
    lineHeight: 24,
    fontFamily: 'System',
  },
  romantic_accountCard: {
    marginBottom: 15,
    borderRadius: 15,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.08,
    shadowRadius: 20,
    elevation: 3,
    backgroundColor: 'white',
    maxWidth: 400,
    alignSelf: 'center',
    width: '100%',
  },
  romantic_accountHeader: {
    overflow: 'hidden',
  },
  romantic_accountHeaderGradient: {
    padding: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  romantic_accountHeaderGradient: {
    padding: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  romantic_accountHeaderText: {
    color: 'white',
    fontSize: 15,
    fontWeight: '500',
    fontFamily: 'System',
  },
  romantic_accountArrow: {
    color: 'white',
    fontSize: 18,
  },
  romantic_accountContent: {
    backgroundColor: 'white',
    padding: 25,
  },
  romantic_accountItem: {
    marginBottom: 20,
  },
  romantic_accountName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#8B6F47',
    marginBottom: 8,
    fontFamily: 'System',
  },
  romantic_accountNumber: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8F6F4',
    padding: 15,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E8E4E0',
  },
  romantic_accountNumberText: {
    flex: 1,
    fontSize: 14,
    color: '#8B6F47',
    fontWeight: '500',
    fontFamily: 'System',
  },
  
  // 공유 섹션
  romantic_shareSection: {
    paddingVertical: 30,
    paddingHorizontal: 20,
  },
  romantic_shareButton: {
    borderRadius: 15,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.2,
    shadowRadius: 15,
    elevation: 8,
  },
  romantic_shareButtonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 18,
  },
  romantic_shareButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 10,
  },
  
  // 푸터
  romantic_footerSection: {
    paddingVertical: 60,
    alignItems: 'center',
    position: 'relative',
  },
  romantic_footerTitle: {
    fontFamily: Platform.OS === 'ios' ? 'Playfair Display' : 'serif',
    fontSize: 32,
    color: '#ffffff',
    marginBottom: 20,
  },
  romantic_footerDivider: {
    width: 60,
    height: 1,
    backgroundColor: '#ffffff',
    opacity: 0.5,
    marginBottom: 20,
  },
  romantic_footerMessage: {
    fontSize: 16,
    color: '#ffffff',
    opacity: 0.9,
    textAlign: 'center',
    lineHeight: 26,
  },
  
  // 모달 스타일
  romantic_modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  romantic_modalContent: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    padding: 30,
    width: '90%',
    maxWidth: 400,
  },
  romantic_modalTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#333',
    textAlign: 'center',
  },
  romantic_modalClose: {
    position: 'absolute',
    top: 15,
    right: 15,
  },

  // =================================================================
  // 기존 달력 스타일들
  // =================================================================
  
  // 모던 다크 달력 스타일
  modernCalendar: {
    marginTop: 30,
    width: '100%',
  },
  modernCalendarContainer: {
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  modernCalendarHeader: {
    alignItems: 'center',
    marginBottom: 20,
  },
  modernCalendarTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#667eea',
    letterSpacing: 1,
  },
  modernCalendarWeekDays: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 15,
  },
  modernCalendarWeekDay: {
    fontSize: 11,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.7)',
    width: 35,
    textAlign: 'center',
  },
  modernCalendarWeekendDay: {
    color: '#667eea',
  },
  modernCalendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  modernCalendarDayContainer: {
    width: '14.28%',
    aspectRatio: 1,
    padding: 2,
  },
  modernCalendarDay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
  },
  modernCalendarTargetDay: {
    backgroundColor: '#667eea',
    shadowColor: '#667eea',
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 8,
    elevation: 8,
  },
  modernCalendarToday: {
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
  },
  modernCalendarOtherMonth: {
    opacity: 0.3,
  },
  modernCalendarDayText: {
    fontSize: 14,
    color: '#ffffff',
    fontWeight: '500',
  },
  modernCalendarTargetDayText: {
    fontSize: 14,
    color: '#ffffff',
    fontWeight: '700',
  },
  modernCalendarTodayText: {
    color: '#667eea',
    fontWeight: '600',
  },
  modernCalendarOtherMonthText: {
    color: 'rgba(255,255,255,0.3)',
  },
  modernCalendarWeekendText: {
    color: '#667eea',
  },
  modernCalendarDDayText: {
    fontSize: 8,
    marginTop: 2,
  },
  
  // 한국 전통 달력 스타일
  koreanCalendar: {
    marginTop: 30,
    width: '100%',
  },
  koreanCalendarContainer: {
    borderRadius: 20,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.1,
    shadowRadius: 15,
    elevation: 5,
  },
  koreanCalendarHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  koreanCalendarTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: KoreanColors.elegant.text,
    fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
    paddingHorizontal: 15,
  },
  koreanCalendarDecoLine: {
    flex: 1,
    height: 1,
    backgroundColor: KoreanColors.elegant.accent,
    opacity: 0.5,
  },
  koreanCalendarWeekDays: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 15,
  },
  koreanCalendarWeekDay: {
    fontSize: 12,
    fontWeight: '600',
    color: KoreanColors.elegant.text,
    width: 35,
    textAlign: 'center',
  },
  koreanCalendarWeekendDay: {
    color: KoreanColors.elegant.primary,
  },
  koreanCalendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  koreanCalendarDayContainer: {
    width: '14.28%',
    aspectRatio: 1,
    padding: 2,
  },
  koreanCalendarDay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
  },
  koreanCalendarTargetDay: {
    backgroundColor: KoreanColors.elegant.accent,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 8,
    elevation: 8,
  },
  koreanCalendarToday: {
    backgroundColor: KoreanColors.elegant.secondary,
    borderWidth: 1,
    borderColor: KoreanColors.elegant.primary,
  },
  koreanCalendarOtherMonth: {
    opacity: 0.3,
  },
  koreanCalendarDayText: {
    fontSize: 13,
    color: KoreanColors.elegant.text,
    fontWeight: '500',
  },
  koreanCalendarTargetDayText: {
    fontSize: 13,
    color: '#ffffff',
    fontWeight: '700',
  },
  koreanCalendarTodayText: {
    color: KoreanColors.elegant.primary,
    fontWeight: '600',
  },
  koreanCalendarOtherMonthText: {
    color: 'rgba(26, 32, 44, 0.3)',
  },
  koreanCalendarSundayText: {
    color: '#E53E3E',
  },
  koreanCalendarSaturdayText: {
    color: '#3182CE',
  },
  koreanCalendarDDayText: {
    fontSize: 8,
    marginTop: 2,
  },
  
  // 빈티지 앱 달력 스타일
  vintageCalendar: {
    marginTop: 30,
    width: '100%',
  },
  vintageCalendarContainer: {
    borderRadius: 20,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 15,
    elevation: 8,
  },
  vintageCalendarHeader: {
    padding: 20,
    alignItems: 'center',
    position: 'relative',
  },
  vintageCalendarTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#ffffff',
    letterSpacing: 1,
  },
  vintageCalendarHeaderDeco: {
    position: 'absolute',
    left: 15,
    right: 15,
    top: 15,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  vintageCalendarEmojiLeft: {
    fontSize: 16,
  },
  vintageCalendarEmojiRight: {
    fontSize: 16,
  },
  vintageCalendarContent: {
    backgroundColor: '#ffffff',
    padding: 20,
  },
  vintageCalendarWeekDays: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 15,
  },
  vintageCalendarWeekDay: {
    fontSize: 12,
    fontWeight: '700',
    color: '#2d3436',
    width: 35,
    textAlign: 'center',
  },
  vintageCalendarWeekendDay: {
    color: '#6c5ce7',
  },
  vintageCalendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  vintageCalendarDayContainer: {
    width: '14.28%',
    aspectRatio: 1,
    padding: 2,
  },
  vintageCalendarDay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
  },
  vintageCalendarTargetDay: {
    backgroundColor: '#fd79a8',
    shadowColor: '#fd79a8',
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 8,
    elevation: 8,
  },
  vintageCalendarToday: {
    backgroundColor: '#f1f2f6',
    borderWidth: 2,
    borderColor: '#6c5ce7',
  },
  vintageCalendarOtherMonth: {
    opacity: 0.3,
  },
  vintageCalendarDayText: {
    fontSize: 13,
    color: '#2d3436',
    fontWeight: '500',
  },
  vintageCalendarTargetDayText: {
    fontSize: 13,
    color: '#ffffff',
    fontWeight: '700',
  },
  vintageCalendarTodayText: {
    color: '#6c5ce7',
    fontWeight: '600',
  },
  vintageCalendarOtherMonthText: {
    color: 'rgba(45, 52, 54, 0.3)',
  },
  vintageCalendarWeekendText: {
    color: '#6c5ce7',
  },
  vintageCalendarDDayText: {
    fontSize: 8,
    marginTop: 2,
  },

  // =================================================================
  // Modern Dark Template Styles
  // =================================================================
  modern_container: {
    flex: 1,
    backgroundColor: '#0a0a0a',
  },
  modern_heroSection: {
    height: height,
    position: 'relative',
    overflow: 'hidden',
  },
  modern_mainPhotoContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  modern_heroOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: '60%',
  },
  modern_bgCircle1: {
    position: 'absolute',
    width: 400,
    height: 400,
    borderRadius: 200,
    backgroundColor: '#667eea',
    top: -200,
    left: -100,
  },
  modern_particle: {
    position: 'absolute',
    width: 4,
    height: 4,
    backgroundColor: 'rgba(255,255,255,0.8)',
    borderRadius: 2,
  },
  modern_heroContent: {
    position: 'absolute',
    bottom: 100,
    left: 0,
    right: 0,
    alignItems: 'center',
    zIndex: 10,
    paddingHorizontal: 40,
  },
  modern_heroSubtitle: {
    fontFamily: Platform.OS === 'ios' ? 'Allura' : 'serif',
    fontSize: 16,
    color: 'rgba(255,255,255,0.8)',
    letterSpacing: 2,
    marginBottom: 20,
    fontStyle: 'italic',
  },
  modern_heroTitle: {
    fontFamily: Platform.OS === 'ios' ? 'Great Vibes' : 'serif',
    fontSize: 72,
    color: '#ffffff',
    marginBottom: 30,
    fontStyle: 'italic',
    textShadowColor: 'rgba(102, 126, 234, 0.5)',
    textShadowOffset: { width: 0, height: 4 },
    textShadowRadius: 20,
  },
  modern_heroNamesContainer: {
    marginBottom: 30,
  },
  modern_heroNames: {
    fontFamily: Platform.OS === 'ios' ? 'Playfair Display' : 'serif',
    fontSize: 32,
    color: '#ffffff',
    fontWeight: '400',
    letterSpacing: 2,
    textAlign: 'center',
  },
  modern_heroDate: {
    fontFamily: 'Inter',
    fontSize: 14,
    color: 'rgba(255,255,255,0.9)',
    letterSpacing: 1,
    textAlign: 'center',
    marginBottom: 10,
  },
  modern_heroTime: {
    fontFamily: 'Inter',
    fontSize: 18,
    color: '#667eea',
    fontWeight: '600',
    textAlign: 'center',
  },
  modern_countdownSection: {
    paddingVertical: 80,
    paddingHorizontal: 30,
  },
  modern_sectionContent: {
    alignItems: 'center',
  },
  modern_countdownTitle: {
    fontFamily: Platform.OS === 'ios' ? 'Great Vibes' : 'serif',
    fontSize: 48,
    color: '#ffffff',
    marginBottom: 40,
    fontStyle: 'italic',
    textShadowColor: 'rgba(102, 126, 234, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 10,
  },
  modern_countdownGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 15,
  },
  modern_countdownNumber: {
    fontSize: 32,
    color: '#667eea',
    fontWeight: '700',
    marginBottom: 5,
  },
  modern_countdownLabel: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.8)',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  modern_calendarSection: {
    marginTop: 30,
  },
  modern_gallerySection: {
    backgroundColor: '#111111',
    paddingVertical: 80,
    paddingHorizontal: 30,
  },
  modern_sectionTitle: {
    fontFamily: Platform.OS === 'ios' ? 'Great Vibes' : 'serif',
    fontSize: 48,
    color: '#ffffff',
    marginBottom: 20,
    fontStyle: 'italic',
    textAlign: 'center',
    textShadowColor: 'rgba(102, 126, 234, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 10,
  },
  modern_sectionSubtitle: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.7)',
    marginBottom: 50,
    textAlign: 'center',
  },
  modern_photoGallery: {
    marginBottom: 40,
  },
  modern_photoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    justifyContent: 'center',
  },
  modern_photoGridItem: {
    width: (width - 80) / 3,
    aspectRatio: 1,
  },
  modern_photoGridImage: {
    width: '100%',
    height: '100%',
    borderRadius: 15,
  },
  modern_quoteSection: {
    paddingVertical: 100,
    paddingHorizontal: 40,
  },
  modern_quoteText: {
    fontFamily: Platform.OS === 'ios' ? 'Cormorant Garamond' : 'serif',
    fontSize: 24,
    color: '#ffffff',
    textAlign: 'center',
    lineHeight: 36,
    marginBottom: 30,
    fontStyle: 'italic',
  },
  modern_quoteAuthor: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.7)',
    textAlign: 'center',
    letterSpacing: 2,
  },
  modern_detailsSection: {
    paddingVertical: 80,
    paddingHorizontal: 30,
  },
  modern_detailsCards: {
    gap: 20,
  },
  modern_detailCard: {
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 20,
    padding: 25,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(102, 126, 234, 0.2)',
  },
  modern_detailIcon: {
    fontSize: 32,
    marginBottom: 15,
  },
  modern_detailTitle: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.7)',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 10,
  },
  modern_detailMain: {
    fontSize: 18,
    color: '#667eea',
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 5,
  },
  modern_detailSub: {
    fontSize: 14,
    color: '#ffffff',
    textAlign: 'center',
    lineHeight: 20,
  },
  modern_coupleSection: {
    backgroundColor: '#0a0a0a',
    paddingVertical: 80,
    paddingHorizontal: 30,
  },
  modern_coupleGrid: {
    gap: 40,
  },
  modern_coupleCard: {
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 25,
    padding: 30,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(102, 126, 234, 0.2)',
  },
  modern_couplePhotoContainer: {
    width: 150,
    height: 150,
    borderRadius: 75,
    overflow: 'hidden',
    marginBottom: 25,
    borderWidth: 3,
    borderColor: 'rgba(102, 126, 234, 0.3)',
    position: 'relative',
  },
  modern_couplePhoto: {
    width: '100%',
    height: '100%',
  },
  modern_couplePhotoOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(102, 126, 234, 0.1)',
  },
  modern_coupleName: {
    fontFamily: Platform.OS === 'ios' ? 'Playfair Display' : 'serif',
    fontSize: 28,
    color: '#ffffff',
    marginBottom: 10,
    fontWeight: '400',
  },
  modern_coupleRole: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.7)',
    letterSpacing: 2,
    textTransform: 'uppercase',
    marginBottom: 15,
  },
  modern_coupleParents: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.8)',
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 15,
  },
  modern_contactSection: {
    paddingVertical: 80,
    paddingHorizontal: 30,
  },
  modern_contactGrid: {
    gap: 25,
    marginBottom: 50,
    width: '100%',
  },
  modern_contactCard: {
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(102, 126, 234, 0.2)',
    overflow: 'hidden',
    marginBottom: 10,
  },
  modern_contactButton: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 25,
    width: '100%',
  },
  modern_contactName: {
    fontSize: 16,
    color: '#ffffff',
    fontWeight: '600',
    flex: 1,
  },
  modern_contactBtnContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 20,
    marginLeft: 10,
  },
  modern_contactBtnText: {
    fontSize: 12,
    color: '#ffffff',
    marginLeft: 5,
    fontWeight: '500',
  },
  modern_shareButtonContainer: {
    alignItems: 'center',
    width: '100%',
    marginTop: 20,
  },
  modern_shareButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#667eea',
    paddingHorizontal: 30,
    paddingVertical: 15,
    borderRadius: 25,
    shadowColor: '#667eea',
    shadowOpacity: 0.3,
    shadowRadius: 15,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  modern_shareButtonText: {
    fontSize: 16,
    color: '#ffffff',
    fontWeight: '600',
  },
  modern_donationSection: {
    paddingVertical: 80,
    paddingHorizontal: 30,
  },
  modern_donationTitle: {
    fontFamily: Platform.OS === 'ios' ? 'Great Vibes' : 'serif',
    fontSize: 48,
    color: '#ffffff',
    marginBottom: 20,
    fontStyle: 'italic',
    textAlign: 'center',
    textShadowColor: 'rgba(102, 126, 234, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 10,
  },
  modern_donationSubtitle: {
    fontSize: 16,
    color: 'rgba(255,255,255,0.8)',
    textAlign: 'center',
    marginBottom: 40,
    lineHeight: 24,
  },
  modern_donationButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.9)',
    paddingHorizontal: 40,
    paddingVertical: 18,
    borderRadius: 30,
    shadowColor: '#667eea',
    shadowOpacity: 0.3,
    shadowRadius: 15,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  modern_donationButtonText: {
    fontSize: 18,
    color: '#667eea',
    fontWeight: '700',
  },

  // =================================================================
  // Korean Elegant Template Styles
  // =================================================================
  korean_container: {
    flex: 1,
    backgroundColor: KoreanColors.elegant.light,
  },
  korean_scrollView: {
    flex: 1,
  },
  korean_heroSection: {
    minHeight: height,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    position: 'relative',
  },
  korean_heroContent: {
    alignItems: 'center',
    zIndex: 2,
  },
  korean_mainPhotoContainer: {
    width: width * 0.9,
    height: width * 0.9,
    borderRadius: 20,
    overflow: 'hidden',
    marginBottom: 40,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 15,
  },
  korean_namesContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 30,
  },
  korean_groomName: {
    fontSize: 28,
    fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
    color: KoreanColors.elegant.text,
    fontWeight: '600',
  },
  korean_brideName: {
    fontSize: 28,
    fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
    color: KoreanColors.elegant.text,
    fontWeight: '600',
  },
  korean_heartContainer: {
    marginHorizontal: 15,
  },
  korean_dateContainer: {
    alignItems: 'center',
  },
  korean_dateYear: {
    fontSize: 16,
    color: KoreanColors.elegant.primary,
    marginBottom: 5,
  },
  korean_dateMonthDay: {
    fontSize: 48,
    fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
    color: KoreanColors.elegant.text,
    fontWeight: '300',
    lineHeight: 48,
  },
  korean_dateDayOfWeek: {
    fontSize: 18,
    color: KoreanColors.elegant.primary,
    marginBottom: 10,
  },
  korean_dateTime: {
    fontSize: 16,
    color: KoreanColors.elegant.text,
    fontWeight: '500',
    textAlign: 'center',
  },
  korean_countdownSection: {
    paddingVertical: 50,
    paddingHorizontal: 20,
    position: 'relative',
  },
  korean_countdownGrid: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 15,
  },
  korean_countdownNumber: {
    fontSize: 28,
    color: KoreanColors.elegant.primary,
    fontWeight: '700',
  },
  korean_countdownLabel: {
    fontSize: 12,
    color: KoreanColors.elegant.text,
    fontWeight: '600',
  },
  korean_calendarSection: {
    marginTop: 30,
  },
  korean_messageSection: {
    paddingHorizontal: 30,
    paddingVertical: 50,
    alignItems: 'center',
  },
  korean_coupleSection: {
    paddingHorizontal: 20,
    paddingVertical: 50,
  },
  korean_weddingInfoSection: {
    paddingHorizontal: 20,
    paddingVertical: 50,
    position: 'relative',
  },
  korean_gallerySection: {
    paddingVertical: 50,
  },
  korean_locationSection: {
    paddingHorizontal: 20,
    paddingVertical: 50,
  },
  korean_contributionSection: {
    paddingHorizontal: 20,
    paddingVertical: 50,
    position: 'relative',
  },
  korean_shareSection: {
    paddingHorizontal: 20,
    paddingVertical: 30,
  },
  korean_footerSection: {
    paddingHorizontal: 30,
    paddingVertical: 50,
    alignItems: 'center',
  },
  korean_sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 30,
  },
  korean_sectionTitle: {
    fontSize: 20,
    fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
    color: KoreanColors.elegant.text,
    fontWeight: '600',
    paddingHorizontal: 20,
  },
  korean_decorativeLine: {
    flex: 1,
    height: 1,
    backgroundColor: KoreanColors.elegant.accent,
    opacity: 0.5,
  },
  korean_customMessage: {
    fontSize: 16,
    lineHeight: 28,
    color: KoreanColors.elegant.text,
    textAlign: 'center',
    fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
  },
  korean_coupleGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 15,
  },
  korean_personCard: {
    flex: 1,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 20,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.1,
    shadowRadius: 15,
    elevation: 5,
  },
  korean_personPhotoContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    overflow: 'hidden',
    marginBottom: 15,
  },
  korean_personPhoto: {
    width: '100%',
    height: '100%',
  },
  korean_personName: {
    fontSize: 18,
    fontWeight: '600',
    color: KoreanColors.elegant.text,
    marginBottom: 5,
  },
  korean_personRole: {
    fontSize: 12,
    color: KoreanColors.elegant.primary,
    marginBottom: 10,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  korean_parentNames: {
    fontSize: 12,
    color: KoreanColors.elegant.text,
    textAlign: 'center',
    lineHeight: 18,
    marginBottom: 15,
  },
  korean_contactButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: KoreanColors.elegant.light,
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: KoreanColors.elegant.primary,
  },
  korean_contactButtonText: {
    fontSize: 12,
    color: KoreanColors.elegant.primary,
    marginLeft: 5,
    fontWeight: '500',
  },
  korean_infoCard: {
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderRadius: 20,
    padding: 25,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.1,
    shadowRadius: 15,
    elevation: 5,
  },
  korean_infoRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 20,
  },
  korean_infoIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: KoreanColors.elegant.light,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },
  korean_infoContent: {
    flex: 1,
  },
  korean_infoLabel: {
    fontSize: 12,
    color: KoreanColors.elegant.primary,
    marginBottom: 5,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  korean_infoValue: {
    fontSize: 16,
    color: KoreanColors.elegant.text,
    fontWeight: '600',
    marginBottom: 3,
  },
  korean_infoSubValue: {
    fontSize: 14,
    color: KoreanColors.elegant.text,
    opacity: 0.7,
  },
  korean_galleryScroll: {
    paddingLeft: 20,
  },
  korean_galleryItem: {
    width: width * 0.7,
    height: width * 0.7,
    marginRight: 15,
    borderRadius: 20,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.2,
    shadowRadius: 15,
    elevation: 8,
  },
  korean_galleryImage: {
    width: '100%',
    height: '100%',
  },
  korean_mapContainer: {
    height: 200,
    backgroundColor: KoreanColors.elegant.secondary,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  korean_mapPlaceholder: {
    fontSize: 48,
    marginBottom: 10,
  },
  korean_mapText: {
    fontSize: 14,
    color: KoreanColors.elegant.text,
    opacity: 0.7,
  },
  korean_locationButtons: {
    flexDirection: 'row',
    gap: 15,
  },
  korean_locationButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: KoreanColors.elegant.primary,
    paddingVertical: 15,
    borderRadius: 15,
  },
  korean_locationButtonSecondary: {
    backgroundColor: 'white',
    borderWidth: 2,
    borderColor: KoreanColors.elegant.primary,
  },
  korean_locationButtonText: {
    color: 'white',
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 8,
  },
  korean_locationButtonTextSecondary: {
    color: KoreanColors.elegant.primary,
  },
  korean_contributionCard: {
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderRadius: 20,
    padding: 30,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.1,
    shadowRadius: 15,
    elevation: 5,
  },
  korean_contributionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: KoreanColors.elegant.text,
    marginBottom: 15,
  },
  korean_contributionDescription: {
    fontSize: 14,
    color: KoreanColors.elegant.text,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 25,
  },
  korean_contributionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: KoreanColors.elegant.light,
    paddingHorizontal: 25,
    paddingVertical: 12,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: KoreanColors.elegant.primary,
  },
  korean_contributionButtonText: {
    color: KoreanColors.elegant.primary,
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 8,
  },
  korean_shareButton: {
    borderRadius: 15,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.2,
    shadowRadius: 15,
    elevation: 8,
  },
  korean_shareButtonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 18,
  },
  korean_shareButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 10,
  },
  korean_footerMessage: {
    fontSize: 16,
    color: KoreanColors.elegant.text,
    textAlign: 'center',
    lineHeight: 26,
    marginBottom: 20,
    fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
  },
  korean_footerNames: {
    fontSize: 20,
    fontWeight: '600',
    color: KoreanColors.elegant.primary,
    marginBottom: 10,
  },
  korean_footerDate: {
    fontSize: 14,
    color: KoreanColors.elegant.text,
    opacity: 0.7,
  },

  // =================================================================
  // Vintage App Template Styles
  // =================================================================
  app_container: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  app_statusBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'ios' ? 50 : 25,
    paddingBottom: 10,
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.05)',
  },
  app_statusLeft: {
    flex: 1,
  },
  app_statusCenter: {
    flex: 1,
    alignItems: 'center',
  },
  app_statusTitle: {
    fontSize: 17,
    fontWeight: '600',
    color: '#6c5ce7',
  },
  app_statusRight: {
    flex: 1,
  },
  app_scrollContainer: {
    flex: 1,
  },
  app_heroSection: {
    height: height * 0.85,
    position: 'relative',
    overflow: 'hidden',
  },
  app_mainPhotoContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  app_sparkle: {
    position: 'absolute',
    fontSize: 18,
  },
  app_heroContent: {
    position: 'absolute',
    bottom: 100,
    left: 0,
    right: 0,
    alignItems: 'center',
    zIndex: 10,
    paddingHorizontal: 40,
  },
  app_heroTitle: {
    fontFamily: Platform.OS === 'ios' ? 'Great Vibes' : 'serif',
    fontSize: 64,
    color: '#ffffff',
    marginBottom: 20,
    fontStyle: 'italic',
    textShadowColor: 'rgba(0,0,0,0.3)',
    textShadowOffset: { width: 0, height: 4 },
    textShadowRadius: 20,
  },
  app_heroSubtitle: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.9)',
    textAlign: 'center',
    marginBottom: 15,
    lineHeight: 20,
  },
  app_heroNames: {
    fontSize: 24,
    color: '#ffffff',
    fontWeight: '600',
    letterSpacing: 2,
    marginBottom: 20,
  },
  app_heroDate: {
    fontSize: 13,
    color: 'rgba(255,255,255,0.8)',
    textAlign: 'center',
    marginBottom: 40,
    lineHeight: 18,
  },
  app_scrollHint: {
    position: 'absolute',
    bottom: 30,
    fontSize: 11,
    color: 'rgba(255,255,255,0.7)',
    textAlign: 'center',
    letterSpacing: 1,
  },
  app_countdownSection: {
    paddingVertical: 60,
    paddingHorizontal: 25,
  },
  app_countdownTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#ffffff',
    marginBottom: 10,
    textAlign: 'center',
  },
  app_countdownSubtitle: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.8)',
    textAlign: 'center',
    marginBottom: 30,
  },
  app_countdownGrid: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 15,
  },
  app_countdownNumber: {
    fontSize: 24,
    color: '#ffffff',
    fontWeight: '700',
  },
  app_countdownLabel: {
    fontSize: 11,
    color: 'rgba(255,255,255,0.8)',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  app_calendarSection: {
    marginTop: 30,
  },
  app_sectionContent: {
    alignItems: 'center',
  },
  app_sectionTitle: {
    fontSize: 28,
    fontWeight: '700',
    color: '#2d3436',
    marginBottom: 8,
    textAlign: 'center',
  },
  app_sectionSubtitle: {
    fontSize: 14,
    color: '#636e72',
    textAlign: 'center',
    marginBottom: 40,
  },
  app_gallerySection: {
    backgroundColor: '#ffffff',
    paddingVertical: 80,
    paddingHorizontal: 25,
  },
  app_photoGallery: {
    marginBottom: 30,
  },
  app_photoMasonry: {
    flexDirection: 'row',
    gap: 10,
  },
  app_photoColumn: {
    flex: 1,
    gap: 10,
  },
  app_photoMasonryItem: {
    width: '100%',
    borderRadius: 15,
    backgroundColor: '#f1f2f6',
  },
  app_cardsSection: {
    paddingVertical: 80,
    paddingHorizontal: 25,
  },
  app_infoCards: {
    gap: 20,
  },
  app_infoCard: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    padding: 25,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 15,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
    borderWidth: 1,
    borderColor: 'rgba(108,92,231,0.1)',
  },
  app_cardIcon: {
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  app_cardIconText: {
    fontSize: 24,
  },
  app_cardTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#2d3436',
    marginBottom: 10,
  },
  app_cardDescription: {
    fontSize: 14,
    color: '#636e72',
    lineHeight: 22,
    marginBottom: 8,
  },
  app_cardDetails: {
    fontSize: 12,
    fontWeight: '500',
  },
  app_coupleSection: {
    backgroundColor: '#f8f9fa',
    paddingVertical: 80,
    paddingHorizontal: 25,
  },
  app_coupleCards: {
    gap: 30,
  },
  app_coupleCard: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    padding: 30,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 5,
  },
  app_couplePhotoContainer: {
    width: 120,
    height: 120,
    borderRadius: 60,
    overflow: 'hidden',
    marginBottom: 20,
    borderWidth: 3,
    borderColor: '#f1f2f6',
  },
  app_couplePhoto: {
    width: '100%',
    height: '100%',
  },
  app_coupleName: {
    fontSize: 22,
    fontWeight: '700',
    color: '#2d3436',
    marginBottom: 8,
    textAlign: 'center',
  },
  app_coupleRole: {
    fontSize: 12,
    color: '#6c5ce7',
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 15,
  },
  app_coupleParents: {
    fontSize: 14,
    color: '#636e72',
    textAlign: 'center',
    marginBottom: 15,
    lineHeight: 20,
  },
  app_contactSection: {
    paddingVertical: 80,
    paddingHorizontal: 25,
  },
  app_contactCards: {
    gap: 20,
    marginBottom: 40,
    width: '100%',
  },
  app_contactCard: {
    backgroundColor: '#f8f9fa',
    borderRadius: 15,
    padding: 20,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
    marginBottom: 10,
    width: '100%',
  },
  app_contactAvatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },
  app_contactAvatarText: {
    fontSize: 28,
  },
  app_contactInfo: {
    flex: 1,
  },
  app_contactName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2d3436',
    marginBottom: 3,
  },
  app_contactPhone: {
    fontSize: 13,
    color: '#636e72',
    marginBottom: 3,
  },
  app_contactRole: {
    fontSize: 12,
    color: '#636e72',
  },
  app_contactButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 15,
    marginLeft: 10,
  },
  app_contactButtonText: {
    fontSize: 12,
    color: '#ffffff',
    marginLeft: 5,
    fontWeight: '500',
  },
  app_shareSection: {
    paddingVertical: 80,
    paddingHorizontal: 30,
    alignItems: 'center',
  },
  app_shareTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#ffffff',
    marginBottom: 10,
    textAlign: 'center',
  },
  app_shareSubtitle: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.8)',
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 30,
  },
  app_donationButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.95)',
    paddingHorizontal: 30,
    paddingVertical: 16,
    borderRadius: 25,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 5,
    marginBottom: 20,
  },
  app_donationButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#6c5ce7',
  },
  app_shareButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.3)',
    paddingHorizontal: 30,
    paddingVertical: 15,
    borderRadius: 25,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 5,
    marginBottom: 30,
  },
  app_shareButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#ffffff',
  },
  app_socialButtons: {
    flexDirection: 'row',
    gap: 15,
    flexWrap: 'wrap',
    justifyContent: 'center',
    width: '100%',
  },
  app_socialButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  app_socialButtonText: {
    fontSize: 12,
    color: '#ffffff',
    fontWeight: '600',
    marginLeft: 8,
  },
  romantic_coupleCardsColumn: {
  flexDirection: 'column',
  gap: 40,
  alignItems: 'center',
  marginTop: 50,
},
romantic_coupleCardFull: {
  backgroundColor: 'white',
  borderRadius: 20,
  padding: 40,
  width: '90%',
  maxWidth: 320,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 10 },
  shadowOpacity: 0.08,
  shadowRadius: 30,
  elevation: 5,
  alignItems: 'center',
},

  // =================================================================
  // 새로운 축하금 안내 디자인 스타일
  // =================================================================
  romantic_giftSection: {
    backgroundColor: '#f8f9fa',
    padding: 32,
    margin: 0,
  },
  romantic_giftHeader: {
    alignItems: 'center',
    marginBottom: 24,
  },
  romantic_giftIconContainer: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#FFF8F4',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
    shadowColor: '#D4A574',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 4,
  },
  romantic_giftTitleContainer: {
    flex: 1,
  },
  romantic_giftTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#191f28',
    marginBottom: 8,
    letterSpacing: -0.5,
    textAlign: 'center',
  },
  romantic_giftSubtitle: {
    fontSize: 16,
    color: '#8b95a1',
    fontWeight: '400',
    margin: 0,
    textAlign: 'center',
  },
  romantic_giftDescription: {
    alignItems: 'center',
    marginBottom: 32,
  },
  romantic_giftDescriptionText: {
    fontSize: 15,
    color: '#4e5968',
    lineHeight: 22,
    fontWeight: '400',
    margin: 0,
    textAlign: 'center',
  },
  
  // 계좌 카드 스타일
  romantic_giftCard: {
    backgroundColor: '#FEFEFE',
    borderRadius: 16,
    marginBottom: 16,
    shadowColor: '#D4A574',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 4,
    borderWidth: 1,
    borderColor: '#F5F0EA',
  },
  romantic_giftCardHeader: {
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    overflow: 'hidden',
  },
  romantic_giftCardHeaderGradient: {
    padding: 16,
  },
  romantic_giftCardHeaderContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  romantic_giftCardHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  romantic_giftCardHeaderText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#D4A574',
    marginLeft: 8,
    letterSpacing: -0.3,
  },
  romantic_giftCardContent: {
    padding: 20,
    paddingTop: 16,
  },
  
  // 계좌 아이템 스타일
  romantic_giftAccountItem: {
    marginBottom: 20,
    borderRadius: 12,
    backgroundColor: '#FDFBF8',
    borderWidth: 1,
    borderColor: '#F0E8DC',
  },
  romantic_giftAccountHeader: {
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F0E8DC',
  },
  romantic_giftAccountName: {
    fontSize: 15,
    fontWeight: '600',
    color: '#8B5A3C',
    textAlign: 'center',
  },
  romantic_giftAccountInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    backgroundColor: '#FFFFFF',
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
  },
  romantic_giftAccountDetails: {
    flex: 1,
  },
  romantic_giftBankName: {
    fontSize: 13,
    fontWeight: '600',
    color: '#A67B5B',
    marginBottom: 4,
    letterSpacing: -0.2,
  },
  romantic_giftAccountNumber: {
    fontSize: 16,
    fontWeight: '700',
    color: '#5D4037',
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    letterSpacing: 0.5,
  },
  romantic_giftCopyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF8F4',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#F0E6D8',
  },
  romantic_giftCopyText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#D4A574',
    marginLeft: 4,
    letterSpacing: -0.1,
  },

  // 웹 버전 스타일 토글 버튼
  romantic_toggleContainer: {
    marginBottom: 30,
    alignItems: 'center',
  },
  romantic_toggleButtons: {
    flexDirection: 'row',
    backgroundColor: '#f2f4f6',
    borderRadius: 12,
    padding: 4,
  },
  romantic_toggleButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 80,
    backgroundColor: 'transparent',
  },
  romantic_toggleButtonActive: {
    backgroundColor: 'white',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 1,
  },
  romantic_toggleButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#8b95a1',
  },
  romantic_toggleButtonTextActive: {
    color: '#191f28',
  },

  // 웹 버전 스타일 계좌 컨테이너
  romantic_accountsContainer: {
    minHeight: 200,
  },
  romantic_accountGroup: {
    marginBottom: 20,
  },
  romantic_accountCards: {
    gap: 12,
  },
  romantic_accountCard: {
    backgroundColor: '#fff',
    borderRadius: 15,
    padding: 24,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 4,
    borderWidth: 1,
    borderColor: '#f0f0f0',
  },
  romantic_accountInfo: {
    flex: 1,
  },
  romantic_accountName: {
    fontSize: 18,
    fontWeight: '700',
    color: '#333',
    marginBottom: 8,
  },
  romantic_bankInfo: {
    marginBottom: 4,
  },
  romantic_bankName: {
    fontSize: 14,
    color: '#888',
    fontWeight: '500',
    marginBottom: 4,
  },
  romantic_accountNumber: {
    fontSize: 20,
    color: '#333',
    fontWeight: '700',
    letterSpacing: 1,
  },
  romantic_copyButton: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    paddingHorizontal: 16,
    backgroundColor: '#3182f6',
    borderRadius: 8,
    minWidth: 60,
    height: 36,
  },
  romantic_copyIcon: {
    fontSize: 13,
    fontWeight: '600',
    color: 'white',
    letterSpacing: -0.3,
  },
  
});

export default styles;