export const STUDIO_DECORATION_ELEMENTS = [
  {
    id: "eucalyptus-branch-top-right",
    label: "유칼립투스",
    source: require("../../../../assets/studio/elements/1-eucalyptus-branch-top-right.png"),
    thumbSource: require("../../../../assets/studio/elements/thumbs/1-eucalyptus-branch-top-right.png"),
  },
  {
    id: "white-flowers-bottom-left",
    label: "화이트 플라워",
    source: require("../../../../assets/studio/elements/2-white-flowers-bottom-left.png"),
    thumbSource: require("../../../../assets/studio/elements/thumbs/2-white-flowers-bottom-left.png"),
  },
  {
    id: "eucalyptus-single-short",
    label: "작은 잎가지",
    source: require("../../../../assets/studio/elements/3-eucalyptus-single-short.png"),
    thumbSource: require("../../../../assets/studio/elements/thumbs/3-eucalyptus-single-short.png"),
  },
  {
    id: "white-peony-single",
    label: "작약 한송이",
    source: require("../../../../assets/studio/elements/4-white-peony-single.png"),
    thumbSource: require("../../../../assets/studio/elements/thumbs/4-white-peony-single.png"),
  },
  {
    id: "white-peony-cluster",
    label: "작약 묶음",
    source: require("../../../../assets/studio/elements/5-white-peony-cluster.png"),
    thumbSource: require("../../../../assets/studio/elements/thumbs/5-white-peony-cluster.png"),
  },
  {
    id: "babies-breath-small",
    label: "안개꽃",
    source: require("../../../../assets/studio/elements/6-babies-breath-small.png"),
    thumbSource: require("../../../../assets/studio/elements/thumbs/6-babies-breath-small.png"),
  },
  {
    id: "olive-branch",
    label: "올리브",
    source: require("../../../../assets/studio/elements/7-olive-branch.png"),
    thumbSource: require("../../../../assets/studio/elements/thumbs/7-olive-branch.png"),
  },
  {
    id: "lavender-stems",
    label: "라벤더",
    source: require("../../../../assets/studio/elements/8-lavender-stems.png"),
    thumbSource: require("../../../../assets/studio/elements/thumbs/8-lavender-stems.png"),
  },
  {
    id: "ranunculus-cream",
    label: "라넌큘러스",
    source: require("../../../../assets/studio/elements/9-ranunculus-cream.png"),
    thumbSource: require("../../../../assets/studio/elements/thumbs/9-ranunculus-cream.png"),
  },
  {
    id: "single-leaf-small",
    label: "작은 잎",
    source: require("../../../../assets/studio/elements/10-single-leaf-small.png"),
    thumbSource: require("../../../../assets/studio/elements/thumbs/10-single-leaf-small.png"),
  },
  {
    id: "rose-bud-dusty",
    label: "장미 봉오리",
    source: require("../../../../assets/studio/elements/11-rose-bud-dusty.png"),
    thumbSource: require("../../../../assets/studio/elements/thumbs/11-rose-bud-dusty.png"),
  },
  {
    id: "magnolia-petals",
    label: "목련",
    source: require("../../../../assets/studio/elements/12-magnolia-petals.png"),
    thumbSource: require("../../../../assets/studio/elements/thumbs/12-magnolia-petals.png"),
  },
  {
    id: "cherry-blossom-branch",
    label: "벚꽃 가지",
    source: require("../../../../assets/studio/elements/13-cherry-blossom-branch.png"),
    thumbSource: require("../../../../assets/studio/elements/thumbs/13-cherry-blossom-branch.png"),
  },
  {
    id: "cotton-flower",
    label: "목화",
    source: require("../../../../assets/studio/elements/14-cotton-flower.png"),
    thumbSource: require("../../../../assets/studio/elements/thumbs/14-cotton-flower.png"),
  },
  {
    id: "pampas-small",
    label: "팜파스",
    source: require("../../../../assets/studio/elements/15-pampas-small.png"),
    thumbSource: require("../../../../assets/studio/elements/thumbs/15-pampas-small.png"),
  },
  {
    id: "greenery-mixed-small",
    label: "그리너리",
    source: require("../../../../assets/studio/elements/16-greenery-mixed-small.png"),
    thumbSource: require("../../../../assets/studio/elements/thumbs/16-greenery-mixed-small.png"),
  },
  {
    id: "divider-leaves-horizontal",
    label: "잎 구분선",
    source: require("../../../../assets/studio/elements/17-divider-leaves-horizontal.png"),
    thumbSource: require("../../../../assets/studio/elements/thumbs/17-divider-leaves-horizontal.png"),
  },
  {
    id: "divider-flower-horizontal",
    label: "꽃 구분선",
    source: require("../../../../assets/studio/elements/18-divider-flower-horizontal.png"),
    thumbSource: require("../../../../assets/studio/elements/thumbs/18-divider-flower-horizontal.png"),
  },
  {
    id: "corner-ornament",
    label: "코너 장식",
    source: require("../../../../assets/studio/elements/19-corner-ornament.png"),
    thumbSource: require("../../../../assets/studio/elements/thumbs/19-corner-ornament.png"),
  },
  {
    id: "divider-wave-script",
    label: "웨이브",
    source: require("../../../../assets/studio/elements/20-divider-wave-script.png"),
    thumbSource: require("../../../../assets/studio/elements/thumbs/20-divider-wave-script.png"),
  },
  {
    id: "motif-minimal-plant",
    label: "미니 식물",
    source: require("../../../../assets/studio/elements/21-motif-minimal-plant.png"),
    thumbSource: require("../../../../assets/studio/elements/thumbs/21-motif-minimal-plant.png"),
  },
  {
    id: "photo-frame-arch",
    label: "아치 프레임",
    source: require("../../../../assets/studio/elements/22-photo-frame-arch.png"),
    thumbSource: require("../../../../assets/studio/elements/thumbs/22-photo-frame-arch.png"),
  },
  {
    id: "photo-frame-circle",
    label: "원형 프레임",
    source: require("../../../../assets/studio/elements/23-photo-frame-circle.png"),
    thumbSource: require("../../../../assets/studio/elements/thumbs/23-photo-frame-circle.png"),
  },
  {
    id: "photo-frame-rectangle",
    label: "사각 프레임",
    source: require("../../../../assets/studio/elements/24-photo-frame-rectangle.png"),
    thumbSource: require("../../../../assets/studio/elements/thumbs/24-photo-frame-rectangle.png"),
  },
  {
    id: "photo-frame-wreath",
    label: "리스 프레임",
    source: require("../../../../assets/studio/elements/25-photo-frame-wreath.png"),
    thumbSource: require("../../../../assets/studio/elements/thumbs/25-photo-frame-wreath.png"),
  },
  {
    id: "photo-frame-drop",
    label: "드롭 프레임",
    source: require("../../../../assets/studio/elements/26-photo-frame-drop.png"),
    thumbSource: require("../../../../assets/studio/elements/thumbs/26-photo-frame-drop.png"),
  },
  {
    id: "map-simple-crossroad",
    label: "약도",
    source: require("../../../../assets/studio/elements/27-map-simple-crossroad.png"),
    thumbSource: require("../../../../assets/studio/elements/thumbs/27-map-simple-crossroad.png"),
  },
  {
    id: "funeral-white-flower-arrangement",
    label: "근조 화분",
    source: require("../../../../assets/studio/elements/28-funeral white flower arrangement.png"),
    thumbSource: require("../../../../assets/studio/elements/thumbs/28-funeral white flower arrangement.png"),
  },
  {
    id: "wedding-divider-champagne-floral",
    label: "샴페인 꽃",
    source: require("../../../../assets/studio/elements/29-wedding divider champagne floral.png"),
    thumbSource: require("../../../../assets/studio/elements/thumbs/29-wedding divider champagne floral.png"),
  },
  {
    id: "wedding-divider-modern-rings",
    label: "반지 구분선",
    source: require("../../../../assets/studio/elements/30-wedding divider modern rings.png"),
    thumbSource: require("../../../../assets/studio/elements/thumbs/30-wedding divider modern rings.png"),
  },
  {
    id: "wedding-ornament-rings-ribbon",
    label: "반지 리본",
    source: require("../../../../assets/studio/elements/31-wedding ornament rings ribbon.png"),
    thumbSource: require("../../../../assets/studio/elements/thumbs/31-wedding ornament rings ribbon.png"),
  },
  {
    id: "wedding-watercolor-bouquet-ornament",
    label: "부케",
    source: require("../../../../assets/studio/elements/32-wedding watercolor bouquet ornament.png"),
    thumbSource: require("../../../../assets/studio/elements/thumbs/32-wedding watercolor bouquet ornament.png"),
  },
  {
    id: "wedding-cake-champagne-ornament",
    label: "케이크",
    source: require("../../../../assets/studio/elements/33-wedding cake champagne ornament.png"),
    thumbSource: require("../../../../assets/studio/elements/thumbs/33-wedding cake champagne ornament.png"),
  },
  {
    id: "wedding-bridal-heels-veil-ornament",
    label: "웨딩 소품",
    source: require("../../../../assets/studio/elements/34-wedding bridal heels veil ornament.png"),
    thumbSource: require("../../../../assets/studio/elements/thumbs/34-wedding bridal heels veil ornament.png"),
  },
  {
    id: "wedding-invitation-envelope-ornament",
    label: "봉투",
    source: require("../../../../assets/studio/elements/35-wedding invitation envelope ornament.png"),
    thumbSource: require("../../../../assets/studio/elements/thumbs/35-wedding invitation envelope ornament.png"),
  },
];

export const getStudioDecorationElement = (elementId) =>
  STUDIO_DECORATION_ELEMENTS.find((item) => item.id === elementId);
